config/routes.rb
Rails.application.routes.draw do
  root 'board#new'

  post '/update_tile', to: "board#update_tile"
  post '/create_board', to: "board#create"
  get '/board/:id', to: "board#show", as: :show_board

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :tiles

  def create_tiles
    tiles_array = []
    (0..2).each do |row_index|
      (0..2).each do |col_index|
        tile = Tile.create(y: row_index, x: col_index)
        tiles_array << tile
      end
    end
    self.tiles << tiles_array
  end

  def rows
    board = []
    (0..2).each do |row_index|
      row = []
      (0..2).each do |col_index|
        tile = self.tiles.find_by(y: row_index, x: col_index)
        row << tile
      end
      board << row
    end
    board
  end

  def json_formatted_rows
    board = []
    (0..2).each do |row_index|
      row = []
      (0..2).each do |col_index|
        tile = self.tiles.find_by(y: row_index, x: col_index)
        row << tile.mark
      end
      board << row
    end
    board
  end

end

app/models/tile.rb
class Tile < ActiveRecord::Base
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def new
  end

  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @board.json_formatted_rows}
    end
  end

  def create
    @board = Board.create()
    @board.create_tiles

    redirect_to  show_board_path(@board.id)
  end

  def update_tile
    tile = Tile.find(params[:id])
    tile.update(mark: params[:mark])
    turn = !("X" == params[:mark])
    tile.board.update(is_xturn: turn )

    respond_to do |format|
      format.json { render json: {hi: "hi"}}
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/board/new.html.erb
<h1><%= link_to("New Game", create_board_path , method: "post") %></h1>

app/views/board/show.html.erb
<h1>The Tic Tac Toe Game</h1>
<table>
<% @board.rows.each do |row| %>
  <tr>
    <% row.each do |tile| %>
    <td data-tile-id=<%= tile.id %> ><%= tile.mark %> </td>
    <% end %>
  </tr>
<% end %>
</table>

<script type="text/javascript">
  var xTurn =  <%= @board.is_xturn %>,
      boardID = <%= @board.id  %>;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TictactoeWorkshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>